version: "3.8"

services:
  featdb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"

volumes:
  mysql: