import UserRoute from "./users.routes";
import SportRoute from "./sports.routes";
import EventRoute from "./events.routes";
import PlayerRoute from "./players.routes";
import LevelRoute from "./levels.routes";
import PositionRoute from "./positions.routes";
import AvailabilityRoute from "./availabilities.routes";
import PeridocityRoute from "./periodicity.routes";
import PersonRoute from './persons.routes';
import AddressRoute from './addresses.routes';
export default { UserRoute ,SportRoute, EventRoute, PlayerRoute, LevelRoute, PositionRoute, AvailabilityRoute, PeridocityRoute,PersonRoute,AddressRoute};
